# Generated by Django 5.1.1 on 2024-09-22 06:50


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.CharField(max_length=255)),
                ('link_type', models.CharField(choices=[('phone', 'Phone Number'), ('url', 'URL')], default='url', max_length=10)),
                ('background_image', models.ImageField(upload_to='hero_images/')),
            ],
        ),
    ]
