# Generated by Django 5.1.1 on 2024-09-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_heroslide_link_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.URLField()),
                ('background_image', models.ImageField(upload_to='hero_images/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HeroSlide',
        ),
    ]
