# Generated by Django 5.1.1 on 2024-09-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_herosection_delete_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='link_type',
            field=models.CharField(choices=[('url', 'External URL'), ('tel', 'Phone Link'), ('scroll', 'Scroll to Section')], default='url', max_length=10),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_link',
            field=models.CharField(max_length=200),
        ),
    ]
