# Generated by Django 5.1.1 on 2024-09-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_googlereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlereview',
            name='star_rating',
            field=models.IntegerField(default=5),
        ),
    ]
